### ISSUE TITLE
Renderer.screen doesn't update on screen size change

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#101]
If you change the size your screen the Renderer.screen methods don't update and remain with the old screen size.

**Comment by kerbybit** [comment]
It works fine for me. Could you post some example code where its not working?

This is code that I used to test it: 
```javascript
register("tick", "testScreen");
function testScreen() {
	ChatLib.chat(Renderer.screen.getWidth() + " " + Renderer.screen.getHeight());
}
```

proof of it working: https://i.imgur.com/WaBIgTB.png

**Comment by SylentButDedly** [comment]
Ah wait nevermind I see the issue, it's just that the Renderer object is defined on initialization, not upon render, so the width and height never get updated
