### ISSUE TITLE
Can we get a way to get the TextComponent of an event message

### ISSUE THREAD

**Issue by WalshyDev** [ChatTriggers/ChatTriggers#121]
I would like to get the TextComponent of an event message so that I can see the hover text, click text or whatever.

**Comment by FalseHonesty** [comment]
An interesting proposition. Currently you can get Minecraft's TextComponent class from the event, however, that is not wrapped and will require you to use obfuscated methods. I believe that @kerbybit is going to try and work on this, I will update this issue with what he does.

**Comment by WalshyDev** [comment]
Appreciated! Thank you for the response.

**Comment by kerbybit** [comment]
Added with 5eceba818d072d56afc48ade1d86df05999cdc08
```javascript
// example
register("chat", function(event) {
	new Message(event).chat();
});
```
