### ISSUE TITLE
Running /ct console while console is already open and printing errors freezes the game

### ISSUE THREAD

**Issue by ThePoptartCrpr** [ChatTriggers/ChatTriggers#133]
If the console has already been opened and is currently printing an error, running /ct console again will completely freeze the game. This is only replicable if the console is currently printing an error (not a normal log), e.g. an error being spammed on the step event, like so:

```js
register("step", function() {
    prinet("e");
});
```

Since `prinet` is obviously not defined, you'll get a big fancy error spammed in your face every step. This is all well and good until you run `/ct console` again, where the game will completely freeze and require a forcible restart.

**Comment by kerbybit** [comment]
Should be fixed in 0.17. if not, reopen issue
