### ISSUE TITLE
Properly escape color codes

### ISSUE THREAD

**Issue by Dennis-Mulder** [ChatTriggers/ChatTriggers#158]
Allow users to escape color codes.

**Current situation:**
"\\&4 ....." turns into "\&4 ....."
"\&4 ....." turns the " ....." into a dark red text

Atm there is a workaround: add invisible modifiers to the string (Credit to Reinified#2891) 
"&&r4 ....." turns into "&4 ....."

tested on CT 0.16.6 in Minecraft 1.12.2

**Comment by kerbybit** [comment]
Either a &r or constructing a text/message object in formatted or unformatted parts is the best way to handle this. Adding an escape for \& might cause other unforseen issues that I would rather not spaghetti code solve
