### ISSUE TITLE
0.18.1 couldn't run the input in default console

### ISSUE THREAD

**Issue by ZekerZhayard** [ChatTriggers/ChatTriggers#162]
Minecraft Version: 1.8.9
Forge Version: 11.15.1.1722

1. Run `/ct console`.
1. Input `ChatLib.chat("Hello World!")` to the console.
1. `Hello World!` would be shown in chat gui in 0.16.6 but nothing happened in 0.18.1.

**Comment by Flonja** [comment]
Use /ct console js
