### ISSUE TITLE
1.14 support?

### ISSUE THREAD

**Issue by SteveTheEngineer** [ChatTriggers/ChatTriggers#165]

**Comment by FalseHonesty** [comment]
1.14 support is not really something we're focused on right now. This would involve porting the mod to a completely new mod loading system, which isn't trivial. I do believe this will come in the future though, sooner or later.

Of course, as always, we're willing to accept any PRs made for this issue!

**Comment by mattco98** [comment]
Multiversion support is WIP, although of course it will not include 1.14.
