### ISSUE TITLE
0.18.4 Crashes on Initial Startup with LiteLoader installed

### ISSUE THREAD

**Issue by Ryah** [ChatTriggers/ChatTriggers#168]
Used MultiMC. Minecraft verison 1.8.9, Forge 11.15.1.1722, Liteloader 1.8.9-SNAPSHOT all installed. No other mods were installed other than ChatTriggers (although they are disabled, this error shows up even when it's the only one installed).

Unable to take a screenshot since Minecraft doesn't start at all.

Log: [https://pastebin.com/BuYG78Jp](https://pastebin.com/BuYG78Jp)

**Comment by FalseHonesty** [comment]
We currently don't support LiteLoader, though it looks like this issue might be solvable via relocation of our Mixins dependency (LiteLoader must ship with their own version or something?). We'll put this one on the backburner, but getting it solved for 1.0.0 might be nice.

**Comment by mattco98** [comment]
No longer a problem after the switch from Mixins to ASM.
