### ISSUE TITLE
Threads not working 1.0

### ISSUE THREAD

**Issue by Heknon** [ChatTriggers/ChatTriggers#170]
Using threads in 1.0 doesn't work. For example, this doesn't work (Doesn't crash or anything. no error just doesn't work..): 
```
new Thread(function() {
  ChatLib.command('lobby');
  Thread.sleep(3000); // or some other delay amount
  ChatLib.command('play skyblock');
}).start();

**Comment by FalseHonesty** [comment]
Should be closed in 2c1fde3426cee5e21b9b98fa84e0c88c4a4628e2.
