### ISSUE TITLE
Latest Version (0.18.4) says it needs to be updated in order to work upon start

### ISSUE THREAD

**Issue by ConradValois** [ChatTriggers/ChatTriggers#172]
So I ran into the issue that the mod sends a chat message saying that the mod needs to be updated to work properly even though im using the latest version (stable 0.18.4). Normally this wouldnt really be an issue for me but the command /ct settings crashes/freezes the game and settings commands of imported modules also freeze the screen until you press esc.  I dont know how to fix this problem because as I said before I'm using the latest version.

**Comment by ConradValois** [comment]
I dont think I need to add steps to reproduce, it should be quite obvious. 
![2019-10-16_17 40 29](https://user-images.githubusercontent.com/28946264/66935593-86b19600-f03c-11e9-848c-59b72093aded.png)

**Comment by ConradValois** [comment]
<img width="130" alt="Bildschirmfoto 2019-10-16 um 17 44 23" src="https://user-images.githubusercontent.com/28946264/66935646-a5179180-f03c-11e9-84f5-fb0bf8ee2f65.png">

**Comment by FalseHonesty** [comment]
This is a bug with the version checking in 0.18.4, all versions after will no longer have that issue. Thanks for reporting anyways!
