### ISSUE TITLE
Client.gui.close() does not properly close the GUI on the server side (CT 1.0.0)

### ISSUE THREAD

**Issue by jhmaster2000** [ChatTriggers/ChatTriggers#174]
**Describe the bug**
Running `Client.gui.close()` only closes the opened gui on the client's side, but the gui stays open on the server side

**To Reproduce**
This is the way I came across the bug and is the easiest way to see it actually happening:
1. Get AutoHarp module and enable it
2. /ct console js
3. Start a song on the Harp (Public or Private, I did on Private)
4. Go to console and type `Client.gui.close()` then press enter
5. Go back in-game to see the Harp GUI is gone but AutoHarp is still playing
6. Attempt to fix the bug
7. Fail to do step 6
8. Procrastinate
9. Try to fix the bug again
10. Succeed at fixing the bug

**Expected behavior**
The GUI is closed both client and server side

**Setup (please complete the following information):**
 - OS: Windows 10 Pro
 - ChatTriggers Version: 1.0.0 snapshot
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_221 x64

**Additional context**
This happened at 1am

**Comment by kerbybit** [comment]
Should be fixed with 6a94603cb6c953b4eec909149ff8909e7a7de7d7
I will re-open if it turns out not to be the case
