### ISSUE TITLE
when I type /crank it says that command is not available what am I doing wrong? btw I am playing on a different server than hypixel

### ISSUE THREAD

**Issue by Mythless** [ChatTriggers/ChatTriggers#175]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - ChatTriggers Version: [eg. 0.18.4]
 - Minecraft Version: [eg. 1.8.9]
- Java Version: [eg 1.8.0_231]

**Additional context**

**Comment by kerbybit** [comment]
you have to import the module. it is not built into ChatTriggers and is not a ChatTriggers issue if it is not working.
