### ISSUE TITLE
Issue with auto updating modules with Jar files included

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/ChatTriggers#180]
**Describe the bug**
When a module with a Jar file included gets auto updated and updates the Jar file, it will fail to delete the old Jar file because it is already in use

**To Reproduce**
1. update module with new jar
2. launch minecraft
3. break things

**Expected behavior**
Either the auto-updating should happen before Jar loading so Jars can be properly deleted if necessary or have a way to unload Jars for deleting

**Comment by mattco98** [comment]
Module loading happens after module updating, so on launch this is not an issue. It is likely to cause issues when updating while in game, but there's not much we can do about it.
