### ISSUE TITLE
Game crashes when trying to fetch cape textures in absence of internet connection or website unreachable

### ISSUE THREAD

**Issue by IconPippi** [ChatTriggers/ChatTriggers#183]
**Describe the bug**
When loading in a singleplayer world in the absence of an internet connection or in the event of the ChatTriggers website being unreachable, the moment the camera is switched to third person the client tries to fetch the ChatTriggers cape textures, but inevitably fails causing the game to crash.

**To Reproduce**
1. Disable your internet connection or wait for the ChatTriggers website to be out of service
2. Launch the game
3. Join a singleplayer world
4. Switch to third person view

**Expected behavior**
The client tries to render the player entity model and proceeds to fetch the capes textures from the ChatTriggers website, but fails and crashes the game. The crash report shows a "java.lang.ExceptionInInitializerError" exception at "com.chattriggers.ctjs.utils.capes.LayerCape.doRenderLayer(LayerCape.kt:15)" caused by either
"java.net.ConnectException: Connection timed out: connect" if the website is unreachable, or "java.net.UnknownHostException: www.chattriggers.com" if the internet connection is absent.

**Screenshots**
//

**Setup (please complete the following information):**
 - OS: Windows 10 (amd64) version 10.0 
 - ChatTriggers Version: 1.1.2
 - Minecraft Version: 1.8.9
- Java Version : 1.8.0_51

**Additional context**
//

**Comment by FalseHonesty** [comment]
Fixed in 54be52ccaed5a9180bbc7203f5411c11ca15938c
