### ISSUE TITLE
Minecraft Forge 1.8.9 Black Screen Issue for ctjs-1.2.1

### ISSUE THREAD

**Issue by rngkGit** [ChatTriggers/ChatTriggers#185]
Hi. I installed this mod today and got an issue. After I put the mod in the mods folder, and hit play, i get a black screen and a not responding issue.

1. Go to 'Minecraft'
2. Click on 'Play'
3. See error

![Capture](https://user-images.githubusercontent.com/64713406/80894930-59a99580-8ca5-11ea-97fe-b336b992e942.PNG)
![dasf](https://user-images.githubusercontent.com/64713406/80894931-5adac280-8ca5-11ea-9520-702557b341c4.PNG)

I expected atleast the forge screen but didnt get there. Other mods work just fine

 - OS: Windows 10 Pro 1909 Build 18363.778
 - ChatTriggers Version: 1.2.1
 - Minecraft Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
- Java Version: 1.8.0_251-b08

I ran it with only that mod and no modules. I even ran w/o the mod. Reinstalled forge and minecraft and deleted the .minecraft. Virus protection was also off for it.

-rngk

edit: i did nothing and now i boot minecraft 1.8.9 forge without this mod and it just crashes. Not even 1.15.2 runs or anything.

**Comment by Wenenu** [comment]
Hmm... I've been having this problem too. I think it may be outdated forge so why don't you try that. ¯\_(ツ)_/¯

**Comment by 4762957** [comment]
Yea me too

**Comment by Wenenu** [comment]
Also it might be the wrong version. Where did you download it from?

**Comment by rngkGit** [comment]
got it from the chattriggers website https://www.chattriggers.com/ and no, previous version of forge did not work.

**Comment by Wenenu** [comment]
Here. I recently got the mods from a video on YouTube. Here are the files you will need. 
Give me your Google Drive bc I can't share them in this post.

**Comment by rngkGit** [comment]
kehaw06@gmail.com just use that. thanks

**Comment by moistalexander** [comment]
Can you send me them too ive also been having this problem
cjalexoct292005@gmail.com
