### ISSUE TITLE
RegisterPacketReceived Event

### ISSUE THREAD

**Issue by glasss13** [ChatTriggers/ChatTriggers#186]
**Is your feature request related to a problem? Please describe.**
There is a slight problem in the javadocs that states registerPacketSent "runs whenever a packet is sent to the client" while it runs whenever a packet is sent from the client. I originally intended to use it for incoming server packets when I realized the event I intended to use didn't exist.

**Describe the solution you'd like**
I would like for there to be a new event for incoming packets from the server to the client.

**Describe alternatives you've considered**
I've considered using ASM to create the event, which almost certainly would work as far as I'm aware. The downside is I don't really know how to do that and obviously that's not a good excuse but seeing as there is an event for packets being sent it feels like it would be logical for there to be one for receiving as well.

**Additional context**
That's it, sorry for bothering.

**Comment by mattco98** [comment]
The reason it doesn't exist is because it is much harder to implement than detecting when the client sends a packet. We can look into it eventually, but probably not soon.
