### ISSUE TITLE
Minecraft Forge 1.8.9 hardlocks on world loading

### ISSUE THREAD

**Issue by CinnaDev** [ChatTriggers/ChatTriggers#188]
The game hardlocks when loading into a world, Multiplayer or Singleplayer

1, Load up Minecraft Forge 1.8.9 (Latest Version)
2. Try to enter a singleplayer world or a server'
3. Wait

Should load into the world but it doesn't

![07-18-2020_07:53:03](https://user-images.githubusercontent.com/61021879/87852243-41bdd700-c8ce-11ea-8966-2de8b3abf839.png)

System settings and Software info
 - OS: Ubuntu Focal Fossa 20.04 LTS
 - ChatTriggers Version: 1.2.2
 - Minecraft Version: 1.8.9 (Forge)
- Java Version: openjdk-8-jre (8u252-b09-1ubuntu1)

**Comment by mattco98** [comment]
This is definitely a you-issue; no one else seems to have this issue. We're at least going to need some logs to figure out what's going on.
