### ISSUE TITLE
Print Chat To Console causes game freeze with certain characters

### ISSUE THREAD

**Issue by KrisAphalon** [ChatTriggers/ChatTriggers#191]
**Describe the bug**
With "Print Chat To Console" option checked, some characters seem to freeze whole game. It then needs to be forcefully closed. I experienced this behaviour mc.hypixel.net with legendary drop from chest. I think the `▬▬` characters might be what's causing this.

**To Reproduce**
1. Log in to mc.hypixel.net
2. Make sure you have "Print Chat To Console" option checked in `/ct settings`
3. Wait for a while for someone to open up legendary drop from chest or open some chests yourself.
OR
Walk up to lobby race and try to start it. The closest one would be in prototype lobby, to the right.

**Expected behavior**
Game shouldn't freeze regardless of the option being checked or not.

**Screenshots**
Example of a message that seem to freeze the game. With option checked it doesn't appear on the chat before freeze.
![message](https://user-images.githubusercontent.com/25371882/88454691-92ef3d00-ce71-11ea-88b5-399015e18ea5.png)

**Setup (please complete the following information):**
 - OS: Linux 5.8.0-rc6-sparky-amd64
 - ChatTriggers Version: 1.2.2
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - Java Version: 1.8.0_252

**Additional context**
In game's logs, the message that freezes the game looks like this:
```
[12:27:18] [Client thread/INFO]: [CHAT] ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
           Mystery Box

  You found loot!
  1x Legendary Superhero Cloak 
  32x Pet Items 

▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
```

This character doesn't only appear in this one place, so fatal freezes are certain when playing with this option turned on.

**Comment by KrisAphalon** [comment]
Bug still present in 1.3, but it seems to freeze only if you have console opened up while problematic text appears.

**Comment by mattco98** [comment]
Doesn't appear to be an issue on the latest version (`essential` branch).
