### ISSUE TITLE
renderBossHealth trigger and registerRenderBossHealth function not getting called

### ISSUE THREAD

**Issue by luffykazuma** [ChatTriggers/ChatTriggers#199]
**Bug**
renderBossHealth and registerRenderBossHealth triggers/functions are not working. They do not get called when the boss bar is about to be drawn.

**To Reproduce**
Attempt both ways as shown here:

```
var bossHealthTrigger = TriggerRegister.registerRenderBossHealth(bossHealthUpdate);

function bossHealthUpdate() {
  ChatLib.chat("BossHealth Updates");
}
```

OR

```
register('renderBossHealth', (event) => {
  ChatLib.chat("BossHealth shown");
})
```

These triggers do not get called when a boss bar is being drawn.

**Expected behavior**
Triggers should be called when boss bar is being drawn.

**Screenshots**
No errors in console whatsoever.

**Setup:**
 - OS: Windows
 - ChatTriggers Version: 1.3.0
 - Minecraft Version: 1.8.9
 - Java Version: 1.8.0_261

**Comment by mattco98** [comment]
Appears to be fixed on master.
