### ISSUE TITLE
/ct load improvement

### ISSUE THREAD

**Issue by Soopyboo32** [ChatTriggers/ChatTriggers#201]
Either add an option to not check for updates when running /ct load
Or make it check for updates of all modules at the same time

because if u have Australian ping + like 20 modules it takes over 15 seconds to check for updates

if u  make it check for updates of all modules at the same time it should also improve boot time

**Comment by kerbybit** [comment]
Added in release [1.3.1](https://github.com/ChatTriggers/ChatTriggers/releases/tag/1.3.1)
