### ISSUE TITLE
Forge wont launch using ct

### ISSUE THREAD

**Issue by zivnadel** [ChatTriggers/ChatTriggers#204]
I launched my minecraft using forge today, but nothing happened. Task manager said java was running in the background but minecraft didnt open. i tried to remove my mods 1 by 1 and when i removed chat triggers everything worked fine. 
why is it not working?

**Comment by CrispyCatto** [comment]
omg this is happening to me aswell i was about to do a report

**Comment by zivnadel** [comment]
probably a new bug or glitch

**Comment by zivnadel** [comment]
also chat triggers website is down for me

**Comment by CrispyCatto** [comment]
same, website and mod arent working

**Comment by phasmm** [comment]
This is also happening to me, glad to see it's not only happening to me

**Comment by kerbybit** [comment]
There is currently an issue with ChatTriggers where if the website is down or unreachable (no internet) the game will take forever to load. As soon as we get the website back up, we will look into fixing this issue

**Comment by CrispyCatto** [comment]
o ok ty

**Comment by zivnadel** [comment]
ok thx

**Comment by phasmm** [comment]
ok ty kerby

**Comment by FalseHonesty** [comment]
This has been fixed, the website is now back up and the mod should run normally. Sorry for the downtime, hope it hasn't been too big of an issue. Thanks for your help guys!
