### ISSUE TITLE
Chattriggers compatibility

### ISSUE THREAD

**Issue by An-Eagle** [ChatTriggers/ChatTriggers#207]
**Describe the bug**
Chattriggers freezes my display totally.
**To Reproduce**
1. install Minecraft
2. Click on Install forge 1.8.9
3. Add the chattriggers mod
4. OS freezes after a while

**Expected behavior**
Normally i should have a working problem
**Screenshots**
Can't screenshot on a frozen pc
**Setup (please complete the following information):**
 - OS: Ubuntu linux
 - ChatTriggers Version: latest, downladed today on the home page - Minecraft Version: 1.8.9
- Java Version: java 8

**Additional context**

**Comment by FalseHonesty** [comment]
Hmm, I've never had any issue with my WHOLE computer freezing, but I did with MC + CT freezing when using the Minecraft Launcher's bundled JRE. Try setting your game profile to use a manually downloaded JRE 8 version, and see how that works.

**Comment by An-Eagle** [comment]
Im already using a manually installed java version. The base jre u get is java 11, and i needed it to be 8

**Comment by An-Eagle** [comment]
Or am i talking jive

**Comment by DJtheRedstoner** [comment]
Are you using OpenJDK? If so try with an oracle jre/jdk.

**Comment by An-Eagle** [comment]
i think im using oracle

**Comment by DJtheRedstoner** [comment]
If you want to, join our discord server ([https://discord.gg/chattriggers](https://discord.gg/chattriggers)), its easier to provide support there.

**Comment by An-Eagle** [comment]
sorry
WHat i meant is i dont think i am
