### ISSUE TITLE
Hangs when using OpenJDK on Ubuntu Focal

### ISSUE THREAD

**Issue by An-Eagle** [ChatTriggers/ChatTriggers#209]
**Describe the bug**
After about 2 minutes Minecraft freezes with this mod enabled

**To Reproduce**
1. Open Minecraft with ChatTriggers active and no modules 
2. Play for a bit
3. Eventually it will freeze, often while warping

**Expected behavior**
Minecraft does not freeze

**Screenshots**

**Setup (please complete the following information):**
 - OS: Ubuntu Focal
 - ChatTriggers Version: 1.3.0 and 0.18.4-SNAPSHOT
 - Minecraft Version:  1.8.9
- Java Version: openjdk version "1.8.0_272"

**Comment by Antonio32A** [comment]
ChatTriggers does not work with your java version on Linux, use java 8 162 which you can get at https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html
You can just download the tar.gz, extract it and point your launcher to extracted/bin/java.

**Comment by Antonio32A** [comment]
> ChatTriggers does not work with your java version on Linux, use java 8 162 which you can get at https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html
> You can just download the tar.gz, extract it and point your launcher to extracted/bin/java.

Also that java version isn't the only one which works, it's just what I have and what has worked without any issues for me.

**Comment by An-Eagle** [comment]
What does not actually work? OpenJDK is the standard on all Linux distributions. That version of the JDK is riddled with security bugs.

Also, downloading that version of Java enforcing signing in with an Oracle account. If there is any company with whom I do NOT want an account, it is Oracle.

**Comment by Antonio32A** [comment]
> What does not actually work? OpenJDK is the standard on all Linux distributions. That version of the JDK is riddled with security bugs.

I'm actually not sure what doesn't work with it, you're gonna have to ask somebody else but I'm pretty sure that OpenJDK will work, just not your current version of it, like I said before: that version is the one which works fine for me and doesn't cause any issues, you're free to experiment and search for a version which does work.

> Also, downloading that version of Java enforcing signing in with an Oracle account. If there is any company with whom I do NOT want an account, it is Oracle.

Aware of this, I don't know if there's anything you can do about it other than just using a throwaway account.
