### ISSUE TITLE
Freezes minecraft

### ISSUE THREAD

**Issue by civilisedzombie** [ChatTriggers/ChatTriggers#214]
Freezes minecraft

**To Reproduce**
IDK just go into hypixel skyblock

**Setup (please complete the following information):**
 - OS: Ubuntu
 - ChatTriggers Version: 1.3.0
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_275

**Additional context**
I have experimentation table installed and my game just randomly freezes
mostly when:
-swapping lobbies
-interacting with inventory
-typing in chat
it can also crash at random times.
I have tested this without chat triggers and it did not happen.
I know that it is not a java problem because I did not recently update it. same with the mods. and it did work before for several weeks.
if you need any more information I will try to get it for you

**Comment by FalseHonesty** [comment]
Same as #212 and the numerous other freezing reports about ubuntu. I wish I knew the cause, but until we do, you have to downgrade your java version.

**Comment by civilisedzombie** [comment]
like is says, i did not change the version of java, it had been working fine and suddenly not any more. i will not downgrade java but i guess i can remove some modules.

update: did not work for some reason. but earlier it worked on windows. except i almost never play on windows
