### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by UltraBlackLinux** [ChatTriggers/ChatTriggers#216]
**Is your feature request related to a problem? Please describe.**
I am always using 1.16.4

**Describe the solution you'd like**
Fabric, please.

**Describe alternatives you've considered**
Forge, in hope, that patchworkmc has support for 1.16.4 at some point

**Comment by Debuggingss** [comment]
1.8.9 is the only properly maintained version atm iirc. 1.12.2 barely has updates. Porting it to fabric would take very long, basically rewriting the mod.
