### ISSUE TITLE
blockBreak trigger not activating on Servers

### ISSUE THREAD

**Issue by EliteMasterEric** [ChatTriggers/ChatTriggers#219]
**Describe the bug**
When a player breaks a block while on a server, `register("blockBreak")` callback functions will not be triggered.

While playing in single player, this issue does not occur.

**To Reproduce**
1. Create a new module containing the following code:
```
register("blockBreak", (block, player, event) => {
  console.log("BREAK");
});
```
2. Call `/ct console js` to display the console.
3. Log into a single player world and break a block. See that the console displays "BREAK".
4. Log into a multiplayer world and break a block. See that the console does not display "BREAK".

**Expected behavior**
An event should be triggered, allowing the module to respond to it.

**Setup (please complete the following information):**
 - OS: Windows 10
 - ChatTriggers Version: 1.3.0
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_51 64bit

**Additional context**
I wanted to track blocks broken per second, with 20 being the maximum the game allows.

**Comment by FalseHonesty** [comment]
Yeah, so the block break event is a server-side only event, meaning it will only trigger in singleplayer. The best way to do what you're trying to do is probably listening for received packets for now. Eventually we might have a block update trigger or something, but for now, that's your best bet.
