### ISSUE TITLE
When executing a reload while in a settings menu buttons cannot be clicked after

### ISSUE THREAD

**Issue by PrinceBunBun981** [ChatTriggers/ChatTriggers#220]
**Describe the bug**
When in a Settings menu, if you create a button that runs `ChatTriggers.loadCT()` it reloads CT but once it re-opens the menu no buttons can be clicked other than the LoadCT button again.

**To Reproduce**
1. Create a settings menu.
2. Add a clickable text button with `ChatTriggers.loadCT()` in the function.
3. Observe as no other toggleable buttons or tabs can be clicked.

**Expected behavior**
I expected the menu to close and re-open functioning normal with being able to click buttons or navigate to different tabs.

**Setup (please complete the following information):**
 - OS: Windows 10
 - ChatTriggers Version: 1.3.0
 - Minecraft Version: 1.8.9
 - Java Version: 1.8.0_271

**Comment by FalseHonesty** [comment]
If I’m understanding what you’re saying, this isn’t an issue with the mod, rather, it’s an issue with SettingsManager. There is currently a bug where buttons in settings manager do not work properly. Is this what you’re referring to?

**Comment by PrinceBunBun981** [comment]
No they work fine normally but once you reload CT the buttons cannot be clicked anymore and do not work.

**Comment by FalseHonesty** [comment]
I see. Yeah I mean, there's not much to do about that except for having your button automatically close the GUI before reloading CT. Calling ChatTriggers.load() from a CT script is what I would refer to as undefined behaviour and probably should be avoided if possible.

**Comment by PrinceBunBun981** [comment]
Alright, my bad then

**Comment by FalseHonesty** [comment]
No problem, the only reason the function is really available is for use in the console, I suppose that there should be some documentation on the function. Hope you can work around this :)
