### ISSUE TITLE
TrueTick trigger.

### ISSUE THREAD

**Issue by Debuggingss** [ChatTriggers/ChatTriggers#222]
The next release which will be 1.3.2 will quite possibly have the tick trigger fixed meaning it will have a phase check and it will run **20** times a second not **40**. Idea is to revert the change, keep "tick" at 40/s fire rate and add a new trigger called TrueTick which will run 20 times a second **or** pass "phase" variable from the Minecraft Forge event to the ChatTriggers tick trigger so people can implement that check if they want. The reason for this is pretty simple. Many people don't like step triggers because they are skeptical about it so they implement their own tick limiters. People who made countdown timers nearly 99% of the times used tick. Everything will be broken until the module creators rewrite it.

**Comment by FalseHonesty** [comment]
Or i could just release 2.0.0 lol

**Comment by FalseHonesty** [comment]
This issue is just going to be a placeholder for making tick fire at 20 times/s so I can add it to the 2.0.0 milestone.

<sup>also just side note anyone using tick for a timer is going to receive a ban in the chattriggers discord ok thanks for your time :)</sup>
