### ISSUE TITLE
Build Fails While Getting Dependencies

### ISSUE THREAD

**Issue by glasss13** [ChatTriggers/ChatTriggers#225]
**Describe the bug**
When building ChatTriggers for the first time, any dependency hosted on spongepowered 520's.

**To Reproduce**
1. Clone CT repo
2. Follow build instructions

**Expected behavior**
Builds Normally

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - ChatTriggers Version: 1.3.0
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_265

**Additional context**
Same issue can be seen in travis logs [here](https://travis-ci.org/github/ChatTriggers/ChatTriggers/builds/761709302)

**Comment by glasss13** [comment]
I've found that changing the maven URL in the repositories block from `http://repo.spongepowered.org/maven` to `https://repo.spongepowered.org/maven` fixes the issue, although as I'm not sure of the issue in the first place, I can't be confident that this fix is correct or permanent.

**Comment by DJtheRedstoner** [comment]
The sponge maven repository has been moved, see this image for details. ![](https://i.imgur.com/ZKF22Kf.png)

**Comment by glasss13** [comment]
Resolved in #226.
