### ISSUE TITLE
Essential should not be a hard dependency

### ISSUE THREAD

**Issue by Semisol** [ChatTriggers/ChatTriggers#261]
**Is your feature request related to a problem? Please describe.**
Essential is in my opinion [bloat + probably privacy invading][1], and does not offer any value to developers except the GUI libraries + other (which can be shaded and/or done with a custom implementation).

**Describe the solution you'd like**
Essential should not be a hard dependency. It should be up to CT modules to handle how Essential may be unavailable.

**Describe alternatives you've considered**
None, since Essential is a hard dependency

**Additional context**
I also hold a bit of a grudge against Essential due to how their UI has dark patterns and has taken data collection to in my opinion, an extreme level, so take this with a grain of salt.

  [1]: https://semisol.dev/blog/why-to-not-use-essential/

**Comment by mattco98** [comment]
I will most likely end up removing it.

**Comment by brdcat-dev** [comment]
Update on this? I find essential a ridiculous dependency for such a great mod

**Comment by mattco98** [comment]
It can't be removed for the 1.8.9 version since it would be a breaking change, but the new 3.0 beta for the latest fabric version will not have it.
