### ISSUE TITLE
Reload a a specific module

### ISSUE THREAD

**Issue by s1099** [ChatTriggers/ChatTriggers#263]
Add a argument to /ct load which can be used to reload a specific module.

**Comment by KTibow** [comment]
other method: store hashes of files, then compare hashes, only reload the ones that changed
ofc this is just me predicting the https://xyproblem.info/

**Comment by mattco98** [comment]
This would be a non-trivial change, but I can see the benefit. If I were to add this it would be in a release after 2.0. 

> other method: store hashes of files, then compare hashes, only reload the ones that changed
ofc this is just me predicting the https://xyproblem.info/

This doesn't make sense; `/ct load` causes side effects. Plus you can't just reload a single file, since all of the files are loaded together.

**Comment by KTibow** [comment]
what about
```
/ct load: reload all modules that changed, tell the user which ones it's reloading, exclude data files if possible
/ct load [module]: reload only that module
/ct load all: reload all modules
```

**Comment by mattco98** [comment]
If you have a module that is so slow that you want to avoid loading it then you should just delete it. I will absolutely not implement file watching.

**Comment by KTibow** [comment]
> If you have a module that is so slow that you want to avoid loading it then you should just delete it.

isn't that the point of the original issue?

> I will absolutely not implement file watching.

i was thinking of not doing it realtime.

**Comment by mattco98** [comment]
Yeah after some research this isn't really possible without some Rhino hacking, of which we already had to do plenty of to even get it to work in the first place. Plus it's been over a year since I've really worked with Rhino, and I'm not trying to break that streak any time soon.
