### ISSUE TITLE
MC takes 10+ minutes to launch (website down?)

### ISSUE THREAD

**Issue by DimensionalDrift1** [ChatTriggers/ChatTriggers#267]
**Describe the bug**
Minecraft takes upwards of 10 minutes launching with the Chat Triggers .jar file in my mods folder. I tested without other mods, with no mods, and with all my usual mods except chat triggers, and chat triggers seems to be the one causing the issue. Based on what small amount of information I could find from google, I'd hazard a guess that the website being down has something to do with it. I checked for logs, but couldn't find anything relevant. 

**To Reproduce**
1. Have chat triggers in the mods folder
2. CT website is down(?)
3. Launch the game
4. Wait for it to load (10ish minutes later)

**Expected behavior**
Before today, MC would load in ~50 seconds.

**Screenshots**
N/A 

**Setup (please complete the following information):**
 - OS: Windows 10
 - ChatTriggers Version: 1.3.2
 - Minecraft Version: 1.8.9
- Java Version: 16.0.1

**Additional context**
I'd check to ensure my CT is up to date, but the website is down, so I have no way of doing so.
I believe that the website is the issue, since I found a forum post talking about the game not launching with the mod installed, and someone else replied that the website was down. Additionally, the website seemed to be fine a few days ago, and my game was launching fine up until today.

**Comment by DimensionalDrift1** [comment]
Well, the website is back up, and MC is launching fine again. It's definitely related.

**Comment by mattco98** [comment]
Yup, I just restarted the server. If it happens again just remove CT from your mods folder.
