### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Eejit43** [ChatTriggers/ChatTriggers#293]
- OS: Mac
 - ChatTriggers Version: 2.0.3
 - Minecraft Version: 1.8.9
 - Java Version: 17.0.1

Crash log:
[crash-2022-03-10_15.43.17-client.txt](https://github.com/ChatTriggers/ChatTriggers/files/8227083/crash-2022-03-10_15.43.17-client.txt)

**Comment by U5B** [comment]
Could you try Java 8 instead?

**Comment by Eejit43** [comment]
Apologies for my lack of knowledge, but how can I do that? I've had trouble finding a way that works online

**Comment by KTibow** [comment]
What launcher are you using? The official one should have the right version selected by default and MultiMC makes it simple to change it.

**Comment by Eejit43** [comment]
Ah well in that case it is likely using Java 8, I simply found that out from running `$ java --version`, sorry!

**Comment by mattco98** [comment]
If this is still an issue, please reach out on the [Discord](https://discord.gg/chattriggers)
