### ISSUE TITLE
Opacity/alpha incorrect values

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#33]
For the opacity/alpha of rendered shapes/strings, the value of 10 acts as 0 and anything below 10 acts as 255

**Comment by SylentButDedly** [comment]
Should expand on this, it only seems to happen with rendered strings, nothing else

**Comment by SylentButDedly** [comment]
Adding on to this more, the alpha values are different between gui.registerDraw() and TriggerRegister.registerRenderOverlay(). I had a rectangle set to 150 opacity in registerDraw and when I switched it to render overlay it acts as if it's 255 opacity

**Comment by kerbybit** [comment]
Fixed in 5055b09d3a6fc36dfdd440c7642e1d2f042d72c9
