### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Summmr** [ChatTriggers/ChatTriggers#335]
**Describe the bug**
Crashes on startup

**To Reproduce**
Just install the .jar

**Expected behavior**
Launch fail. Works when i remove ctjs

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - ChatTriggers Version: ctjs-2.1.4-1.8.9
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_321-b07

**Comment by camnwalter** [comment]
Can you send your log that contains the crash?

**Comment by Summmr** [comment]
How do i do that?

**Comment by Summmr** [comment]
[latest.log](https://github.com/ChatTriggers/ChatTriggers/files/8905453/latest.log)
It also crashes when i load ct with normal minecraft launcher

**Comment by Summmr** [comment]
[2022-06-15-7.log](https://github.com/ChatTriggers/ChatTriggers/files/8905462/2022-06-15-7.log)
This is in normal launch

**Comment by camnwalter** [comment]
Try with just ChatTriggers, and if it doesn't launch, then it's most likely a launcher that isn't supported by Essential, or something going wrong with Feather Client.

**Comment by Summmr** [comment]
Crashes the same with just cjts in normal mc launch

**Comment by Dawjaw** [comment]
do you also have a log for that? both logs show that the game was started with feather

**Comment by mattco98** [comment]
If this is still an issue, please reach out on the [Discord](https://discord.gg/chattriggers)
