### ISSUE TITLE
Pls fix spelling

### ISSUE THREAD

**Issue by feeoodoor** [ChatTriggers/ChatTriggers#336]
**Describe the bug**
A name of an absolete module is misspelled

**Expected behavior**
I expected spelling to be right

**Screenshots**
![image](https://user-images.githubusercontent.com/92843959/174376392-dc7506fa-b170-4086-a458-eb1ec2cd84c3.png)

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - ChatTriggers Version: [2.1.4]
 - Minecraft Version: [1.8.9]
 - Java Version: [Does it even matter for this bug]

**Additional context**
When switching servers a message was popping up telling me to delete a module "PeristentKeyBinds", there was no module with this exact name

**Comment by mattco98** [comment]
This issue tracker is for issues with the mod. Module functionality is the concern of the module author.
