### ISSUE TITLE
Packet type Criteria for packet events

### ISSUE THREAD

**Issue by Soopyboo32** [ChatTriggers/ChatTriggers#337]
**Is your feature request related to a problem? Please describe.**
Because of the sheer amount of packets that get sent, it can be laggy to have a packet trigger registered even if it returns immediately if the packet is not of the desired type

**Describe the solution you'd like**
An option to have the event only register on a certain packet type that way a large majority of the immediate returns can be just skipped entirely

**Describe alternatives you've considered**
some of the time the same effect can be gained thru other methods, but there is still some situations where the packet trigger is necessary (excluding using asm)

**Comment by mattco98** [comment]
Added in 7571401edeb8ddbd9eaebf606532b2eb50367c6a
