### ISSUE TITLE
Game softlocks shortly after joining server

### ISSUE THREAD

**Issue by lineargraph** [ChatTriggers/ChatTriggers#353]
**Describe the bug**
Shortly after joining a server the game locks up, not accepting any input or rendering anything (resizing the window leads to only the top left part being rendered on). This goes on for 2 minutes or so without change; after that time i close the game.

**To Reproduce**
Could not reproduce the error.

**Expected behavior**
The game should not lock up.

**Screenshots**
There are no screenshots.

**Setup (please complete the following information):**
 - OS: `Linux #1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux`
 - ChatTriggers Version: ctjs-2.1.5-1.8.9.jar
 - Minecraft Version: 1.8.9
- Java Version: openjdk version "1.8.0_345"

**Additional context**

While the lockup was happening i grabbed a stacktrace using `jstack`. Most relevant are probably `RUNNABLE` threads and the `"Client Thread"` (since the client thread is responsible for input and rendering handling): https://hastebin.com/emaculupuc

**Comment by mattco98** [comment]
> Could not reproduce the error. 

So this is a one-off issue? If it's not reproducible, then there's not much we can do.

**Comment by lineargraph** [comment]
Closing, was caused by a module that i overlooked in the stacktrace.
