### ISSUE TITLE
Add Travis support

### ISSUE THREAD

**Issue by FalseHonesty** [ChatTriggers/ChatTriggers#36]
Build userdocs & jar then push to site

**Comment by FalseHonesty** [comment]
Possibly add a github releases deploy, or discord integration?

**Comment by kerbybit** [comment]
Discord integration can be handled by github web hooks. Release deploy is eventually wanted but not an urgent issue so moved to backlog

**Comment by kerbybit** [comment]
Travis needs to be updated with the new host.
Releases should be moved to github as an auto release (we fill in the changes after release)
Javadocs should remain the way that they where, just on the new host
