### ISSUE TITLE
Cross Version Support

### ISSUE THREAD

**Issue by FalseHonesty** [ChatTriggers/ChatTriggers#38]
Have a single jar that will work on versions 1.8.9-1.12.2

**Comment by kerbybit** [comment]
This probably will never work because of mixins now but when we feel like it is time to release 1.0, we will be working on 
- 1.13 version
- possibly a hyperium version
- possibly a 1.7.10 version (highly unlikely but I'll at least take a look)

**Comment by FalseHonesty** [comment]
Mixins will 100% support cross version, much better than anything else in fact. Mixins are by default required to apply or else errors will be thrown, however, this is changeable. We would just have to create several mixins targeting the same functionality for different versions, and that will work perfectly. The issue here is compatibility with forge across versions, as well as environments without forge (namely, Hyperium). Wrappers should be able to use reflection and such to support changing classes, and mixins may be able to take the place of forge events.

**Comment by FalseHonesty** [comment]
With the introduction of the feature/preprocessing branch, cross version compatibility will be able to be achieved in just one code base. Separate jars will still need to be built for each targeted version however.
