### ISSUE TITLE
Seperate libraries & modules

### ISSUE THREAD

**Issue by ixnoahlive** [ChatTriggers/ChatTriggers#383]
**Is your feature request related to a problem? Please describe.**
The problem is that /ct modules is very easily flooded with shitty modules that you can't do much with as a user.

**Describe the solution you'd like**
Move all modules with isRequired to the bottom with a little bit of white space inbetween.

**Comment by Baltrazx** [comment]
iirc this was already talked abt cant remember what the outcome was doe, myb

**Comment by ixnoahlive** [comment]
> and dont talk abt shitty stuff if u got coffee

let's keep personal attacks away from the github

**Comment by ixnoahlive** [comment]
Closing as of PR #385 , which aims to resolve this issue.
