### ISSUE TITLE
Can't import any modules

### ISSUE THREAD

**Issue by Qu4ntvm** [ChatTriggers/ChatTriggers#384]
I keep getting: "Unable to import module [module name]"

**Comment by ImaDoofus** [comment]
It is likely related to this recent issue
https://github.com/ChatTriggers/ChatTriggers/wiki/Fixing-broken-imports

**Comment by kerbybit** [comment]
This has been resolved with a new SSL certificate on the website. Future ChatTriggers version should not have the same issue because they aren't using an outdated version of MC and thus also not using outdated version of Java
