### ISSUE TITLE
Update The Mod

### ISSUE THREAD

**Issue by DEMnetwork** [ChatTriggers/ChatTriggers#387]
**Is your feature request related to a problem? Please describe.**
I'm Using 1.19.4 And Higher With Quilt And That Mod Is For 1.8.9 Witch Is A Very Legacy version

**Describe the solution you'd like**
Seding The Updates To The Newer Versions Of Minecraft And Make It COmpatible With Forge, Fabric And Quilt

**Describe alternatives you've considered**
Send Realeses To The Versions 1.8.9,1.9,1.10,1.11,1.12,1.13.1.14,1.15,1.16,1.17,1.18,1.19 And 1.20

**Additional context**
It Should be Acessible In Newer , Plese UPDATE

**Comment by camnwalter** [comment]
We are currently working on a complete rewrite for Fabric 1.19.4 and 1.20.1, and in the future newer versions as well. Older versions (before 1.19.4) won't be supported unless there are a lot of requests to do so.  See https://github.com/ChatTriggers/ctjs for that repo.

**Comment by mattco98** [comment]
We will most likely never update the mod for Forge. The Fabric update is mostly complete. I believe Quilt is a fork of Fabric and so shouldn't be hard to support, but if it does require significant support, it probably won't happen without an equally significant demand for it. If you want to try out the new 3.0 beta (for 1.19/1.20 Fabric), join our Discord and check our the beta-discussion channel.
