### ISSUE TITLE
Asm doesn't work with mixins

### ISSUE THREAD

**Issue by PolarC** [ChatTriggers/ChatTriggers#389]
Basically when the callbackinfo is cancelled from another forge mod using mixins asm won't work anymore.

For example the mc renderBlock function, when another mod cancels the callback info and replaces it with their own code (for example block highlight), it will not run the asm code that is injected into the function.

This issue could also be feature of asm (real)

**Comment by mattco98** [comment]
As we've told you time and time again, ASM is not safe. If any other mod injects anywhere near where you're injecting, the behavior is essentially undefined. If you don't like it, upgrade and use mixins yourself.
