### ISSUE TITLE
persistent visual glitch

### ISSUE THREAD

**Issue by fightersLeader** [ChatTriggers/ChatTriggers#390]
**Describe the bug**
when i open the game with ct i see either nothing or a bunch of disorganized lines where my is character is supposed to be, if i enter any server or survival world i barely see my surroundings (sice it's dificult to put into words i'll provide screenshots)

**To Reproduce**
i don't know what causes me specifically to have this bug but all i need to do is open the game normally so if you really wanna know:
1 open the minecraft launcer
2 select the forge 1.8.9 version (more specifically: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9)
3 click play
4 on the right of the screen your character should be either absent or replaced by a bunch of lines

**Screenshots**
in the minecraft home screeen
![Cattura](https://github.com/ChatTriggers/ChatTriggers/assets/151957211/b1e4009d-8a4d-425d-9545-0b21f971dff1)

the next two were taken in the hypixel hub but the effect is analogus in any server and/or single player world (note: on the second screenshot you can see another player also being disfigured)
![Cattura2](https://github.com/ChatTriggers/ChatTriggers/assets/151957211/e7b39c57-4178-44cd-aaa9-6ec4d3bccd4f)
![Cattura3](https://github.com/ChatTriggers/ChatTriggers/assets/151957211/c5dbb791-3e44-4a46-a442-777df82c3449)
 

**Setup:**
 - OS: windows 10
 - ChatTriggers Version: 2.2.0
 - Minecraft Version: 1.8.9
- Java Version: 1.8.0_111-b14

**Additional context**
before resorting to the bug report i tried to reboot the game multiple times, restart the computer, completely remove the "ChatTriggers" folder from C:\Users\ (my username)\AppData\Roaming\ .minecraft\config and let it regenerate, re-install the mod file and get rid of the old one and change my skin out of desperation, but the bug is persistent and i deliberately avoided regenerating the .minecraft folder because i don't know how computers work and want to avoid potentially getting myself in a bigger problem.
I hope i gave enough info and made an overall useful report, this is my first time making one so i apologize if i made some mistakes.

**Comment by fightersLeader** [comment]
update: i decided to also regenerate the .minecraft folder and the problem still persists, then i remembered i didn't log into my essentials account for a year and thought (once again out of desperation) that it may have something to do with my problem, it doesn't and now i'm stuck again.

**Comment by mattco98** [comment]
Your Java version is _really_ old, I would try updating that to the latest Java 8 version and see if that fixes it

**Comment by fightersLeader** [comment]
ok, i'll try it when i have time, but it would be wierd if it was that because ct worked when i started using it , the visual glitch happened randomly a copule days ago but i have been using ct for at least a month.

**Comment by fightersLeader** [comment]
i updated java to version 1.8.0_391 but still have the glitch unfortunately

**Comment by fightersLeader** [comment]
i tried to open thegame again without changing anything and the glitch fixed itself.
