### ISSUE TITLE
RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!

### ISSUE THREAD

**Issue by malte9799** [ChatTriggers/ChatTriggers#392]
**Describe the bug**
Game crash on startup

**To Reproduce**
1. Start Game

**Version**
1.20.2 ()

**Setup (please complete the following information):**
 - OS: Windows
 - ChatTriggers Version: 3.0.0-beta.9_1.20.2-fabric
 - Minecraft Version: 1.20.2
- Java Version: 1.8.0_391-b13

**Additional context**
Error log: https://hastebin.com/share/obesojades.css

**Comment by Marvinschs** [comment]
This is the wrong Github repository for bugs related to the [Chattriggers Beta](https://github.com/ChatTriggers/ctjs)
