### ISSUE TITLE
Issue with image download resizing

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#50]
If you use RenderLib.downloadImage() and specify false for whether or not it should resize the image for you, it still downsizes it to 256x256

**Comment by FalseHonesty** [comment]
This isn't quite the case. It downloads to your machine in the default size, but you have to play around with texture width, height, and scale to make it look as you wish. If this ends up _not_ working or being the desired effect, please comment on this issue and I will re-open it.
