### ISSUE TITLE
Module name is exact same as name in metadata breaks things

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#60]
If you have the name in the module metadata the exact same as whatever it's uploaded as, it breaks ctjs. If Minecraft is already open it just freezes during module reload. If you're launching Minecraft it crashes with the following error

```
The game crashed whilst initializing game
Error: java.lang.NumberFormatException: multiple points
```

**Comment by kerbybit** [comment]
possibly fixed in b475a4039d88f9dfde934fd1f4fa210a927f0a09
needs review
