### ISSUE TITLE
ConcurrentModifications crashes still occur

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#61]
Those dumb ConcurrentModifications crashes still happen occasionally when doing /ct load

**Comment by FalseHonesty** [comment]
Could I have a crash report? Thank you!

**Comment by SylentButDedly** [comment]
Kinda didn't realize you asked for this, here's the top of a crash report: https://hastebin.com/igadayejux.txt
If you need more I can pm it to you on discord

**Comment by kerbybit** [comment]
This has been fixed internally (everything loads and unloads properly without tripping over each other in the thread) but may still happen if someone is using a thread in a module. This should be handled via a "gameUnload" trigger to stop running threads, not by us in the mod.
