### ISSUE TITLE
ChatLib.getChatLines() is broke

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#62]
ChatLib.getChatLines() always has an index of 0 and nothing ever gets added to it

**Comment by SylentButDedly** [comment]
Still broken after 0.6.4, now it keeps up to 5 lines of chat and 4 of which are blank lines with color codes

**Comment by kerbybit** [comment]
Fixed as of 917b1314db3ddcb2f83f5febaff040d52b389c34
