### ISSUE TITLE
Add an Item wrapper

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/ChatTriggers#69]
# Goal
Add a new Item wrapper for use as the return in the inventory wrapper. This will allow for more seamless integration with item icons, unlocalized names, registry names and more without over populating the inventory wrapper.

**Comment by kerbybit** [comment]
Added base support in 946abf9f47fd25380530b888549e57ca434d6d66
Needs more "getters" before release
- durability
- tool status
- enchantments
- lore
- and more

**Comment by kerbybit** [comment]
- canPlaceOn(Block)
- canHarvest(Block)
- canDestroy(Block)
added in 81c7dc67827a2fef03bba820cea91a93b9a7c44d

- getEnchantments
started to get added. only returns enchantment ID and level

**Comment by FalseHonesty** [comment]
Should be functional to the point where this issue is completed as of commit e5bc212175bab9fd65fb9135d235536f86d9d8b0. Again, we may want more features in the future, but for now it is fully working with most things that one could need.
