### ISSUE TITLE
Add a Block wrapper

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/ChatTriggers#70]
Similar to the Item wrapper but to replace the return in the looking at wrapper

**Comment by kerbybit** [comment]
Added basic support in 4909b87d96526101e6c44fde27f01c3b0955f914
Added it as a return object for the new Player.lookingAt() method
Needs more "getters"
- metadata
- block state
- redstone level
- mining level
- and more

**Comment by FalseHonesty** [comment]
Added 

- metadata
- block state
- redstone level
- harvest checkers

in a73a0d6

**Comment by FalseHonesty** [comment]
Pretty much in a fully working state as of commit c539eec94239b32de5d50ae6f2c23b03ca9ca980. While we may want more features in the future, I feel that that is out of the scope of this issue, and thus am closing it.
