### ISSUE TITLE
Documentation for Wrappers & Libs

### ISSUE THREAD

**Issue by FalseHonesty** [ChatTriggers/ChatTriggers#71]
The [Minecraft directory](https://github.com/ChatTriggers/ct.js/tree/master/src/main/java/com/chattriggers/ctjs/minecraft) contains most of the user facing code, but still lacks a lot of documentation. Most of these are simple getters and setters so you should be able to look at them and find out what they do, and thus can be easily documented.

**Comment by FalseHonesty** [comment]
Mostly finished in 1a0f3b2856bc84f285b4a558677542117429d182. Libs still have gaps in documentation, but the wrappers are fully documented.

**Comment by qkleinfelter** [comment]
I'll take a look at this later tonight

**Comment by kerbybit** [comment]
Moved to review

Needs one final comb through all of the document comments to make sure that they are present and consistent. That will probably get done right before the 0.9.1/0.10 release.
