### ISSUE TITLE
Inventory rework

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/ChatTriggers#72]
Currently, the inventory object is linked directly to the player and only the player. We want to be able to abstract that object to let it be useful in something like a chest inventory.
# Goals
- abstract the Inventory object
- add a Player getter to get inventory
- add some sort of chest gui getter to get inventory

**Comment by FalseHonesty** [comment]
Mostly implemented in commits 1d1ca5a603189937872028bec637ac23a3baca63 and 29cb011569cbf9044509ead92a1f7756ad1aa18a. However, I do want to add a helper for getting the player's armor, possibly a subclass of Player allowing for an API such as `Player.armor.getHelmet()`.

**Comment by FalseHonesty** [comment]
Should be fully completed as of 11e5781692fd94cfa12a47e02b37db7a43b288cd.
