### ISSUE TITLE
Refactor minecraft/libs directory

### ISSUE THREAD

**Issue by FalseHonesty** [ChatTriggers/ChatTriggers#75]
Currently, there is a split between the `minecraft/libs` and the `minecraft/wrappers` directory. For example, there is a `WorldLib` and a `World` wrapper, which just splits methods between two different objects for no reason.

 I would like to move `WorldLib` into the `World` wrapper, along with all of the other libs that make sense to be in that directory, like `ChatLib` and `FileLib` (Should be renamed to something like `Chat` and `FileSystem`). Then, other things like `MathLib` should be moved out to a top level package, like `/libs` and possibly renamed.

**Comment by kerbybit** [comment]
This has been completed for a while
