### ISSUE TITLE
Client.getCurrentChatMessage() doesn't work

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#86]
No errors but it also doesn't return anything. Setting the chat message works fine, just trying to get the string doesn't

**Comment by FalseHonesty** [comment]
Does setting the chat message work when the chat gui is already open?

**Comment by SylentButDedly** [comment]
Setting it works fine, even if the chat GUI isn't open

**Comment by FalseHonesty** [comment]
Fixed in #100
