### ISSUE TITLE
Scoreboard doesn't update properly

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/ChatTriggers#90]
the Scoreboard wrapper was not properly implemented and never updates its values

**Comment by FalseHonesty** [comment]
Is clearcache ever called?

**Comment by kerbybit** [comment]
probably not. I still blame cham

**Comment by qkleinfelter** [comment]
This worked when we had MinecraftVars because I always called clearcache before the var was reassigned (in providedlibs), so I blame whoever removed MCVars

**Comment by FalseHonesty** [comment]
Confirmed fixed as of commit cd8613e59fc8958c64b8e3f8778ed3be0e8d4cfe
