### ISSUE TITLE
gui.registerMouseReleased() doesn't do what it says

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#92]
Instead of only triggering when you release the mouse, it just spams as long as the mouse is held down

**Comment by SylentButDedly** [comment]
Another issue with getMouseReleased, if the gui closes while you're holding down the mouse it will consider it still dragging when the gui is next opened

**Comment by kerbybit** [comment]
fixed with 21346ecfde7476b56c4e39fe7e831107a17b7bc4
