### ISSUE TITLE
Console randomly scrolling up

### ISSUE THREAD

**Issue by SylentButDedly** [ChatTriggers/ChatTriggers#94]
The console will scroll up occasionally when something gets printed

**Comment by qkleinfelter** [comment]
I always have it scroll to where the newest item is (i.e. scrolling down) when something is printed

**Comment by SylentButDedly** [comment]
That's what it used to do but now it randomly scrolls up, possible only happens when you get a deprecated warning but haven't fully tested it

**Comment by FalseHonesty** [comment]
The console has been highly changed since this, and I haven't heard any reports of this happening anymore. Seems likely to not be an issue any longer.
